version: "3"
services:
  db:
    container_name: studio-startups-database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: startups_studio
    ports:
      - "5432:5432"
    networks:
      - network1

  backend:
    container_name: studio-startups-backend
    depends_on:
      - db
    restart: always
    image: andreyneverovich/studio-startups-backend:latest
    working_dir: /backend
    volumes:
      - ./:/backend
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    networks:
      - network1
    expose:
      - "8080"
    command: "mvn clean spring-boot:run"

networks:
  network1:
    driver: bridge
